# Site settings
title: RespondLC
email: respondlc1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  RespondLC was formed to ensure that all members of the
  Lewis & Clark community feel safe on campus and beyond.
  We build services that bring the community together.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://respondlc.org" # the base hostname & protocol for your site
twitter_username: respondlc
github_username:  respondlc

# Build settings
markdown: kramdown
